In [1]:
#EXPERIMENT	NO	5

In [2]:
#AIM : Creating dimensional array

In [3]:
#name :Snehal gulhane
#Roll no. : 18
#Sec : CSE-DS
#Subject : ET-I

In [4]:
import numpy as np

In [5]:
#creating 1D array. (square bracket in round = array)(square bracket=tuple)
a1=np.array([10,20,30,40])


In [6]:
a1

array([10, 20, 30, 40])

In [7]:
#creating 2D array
a2 = np.array([[11,30,20,40],[34,89,47,34]])

In [8]:
a2

array([[11, 30, 20, 40],
       [34, 89, 47, 34]])

In [9]:
#creating 2D array using matrix
a3=np.matrix('11,23;33,45;67,78')
print(a3)

[[11 23]
 [33 45]
 [67 78]]


In [10]:
# Create array of 25 random integers between 20 and 23 (inclusive)
arr = np.random.randint(20, 24, size=25)
print(arr)

[20 22 20 21 22 20 22 22 20 21 23 21 21 21 20 21 22 22 22 23 22 20 23 23
 23]
